import type { NextPage } from 'next'
import Head from 'next/head'
import { useContext, useEffect } from 'react'
import Layout from '../components/layou/Layout'
import Loader from '../components/Loader'
import { LoadingContext } from '../context/LoadingContext'
import styles from '../styles/Home.module.css'

const Home: NextPage = (props) => {
  const { loading, setLoading } = useContext(LoadingContext)

  useEffect(() => {
    setLoading(true)
    const subscribe = setTimeout(() => {
      setLoading(false)
    }, 5000);
    return () => {
      subscribe
    }
  }, [])
  if (loading) {
    return <Loader />
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>

      </Layout>
    </>
  )
}

export default Home
